pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git https://github.com/Theedsiha/CutoffCalculatorre.git
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}
